### ISSUE TITLE
cargo supposedly not installed while being installed

### ISSUE THREAD

**Issue by Artim96** [dionysius/vaultwarden-deb#11]
I've installed the rust toolchain 1.78 with rustup. But gdb buildpackage for some reason refuses to find cargo:
```
gbp:info: Extracting 'vaultwarden_1.30.5.orig.tar.gz' to '/opt/vaultwarden-deb/vaultwarden-tmp'
gbp:info: Exporting 'HEAD' to '/opt/vaultwarden-deb/vaultwarden-tmp'
gbp:info: Moving '/opt/vaultwarden-deb/vaultwarden-tmp' to '/opt/vaultwarden-deb/vaultwarden-1.30.5'
gbp:info: Performing the build
 dpkg-buildpackage -us -uc -ui -i -I
dpkg-buildpackage: Information: Source package vaultwarden
dpkg-buildpackage: Information: Source version 1.30.5-1
dpkg-buildpackage: Information: source distribution unstable
dpkg-buildpackage: Information: Source changed by dionysius <dragon.dionysius@gmail.com>
 dpkg-source -i -I --before-build .
dpkg-buildpackage: Information: host architecture amd64
dpkg-source: Information: Options from vaultwarden-1.30.5/debian/source/options are used: --extend-diff-ignore=(^|/)(.github|LICENSE|README|signing-key)
dpkg-checkbuilddeps: Error: Unfulfilled build dependencies: cargo
dpkg-buildpackage: Warning: Build dependencies/conflicts not fulfilled; abort
dpkg-buildpackage: Warning: (Use -d to override.)
debuild: fatal error at line 1184:
dpkg-buildpackage -us -uc -ui -i -I failed
gbp:error: 'debuild -i -I' failed: it exited with 29
```
But
```
cargo -V
cargo 1.78.0 (54d8815d0 2024-03-26)
```
```
which cargo
/usr/bin/cargo
```

So what exactly is it complaining about?

**Comment by dionysius** [comment]
Unfortunately https://github.com/dionysius/vaultwarden-deb/blob/main/debian/control#L4 looks for a cargo **package** installed. `e.g. dpkg -l | grep cargo` should list it. I haven't figured out a way to make this optional as there is no `rustup` package in debian.

You have 2 options:
- install `cargo` from your apt sources but still use `rustup toolchain install <version> ` as described in the readme. It should pick your rustup version when building
- remove `cargo` from build-depends in said file and make a temporary git commit before building

**Comment by dionysius** [comment]
Updated and explained the first option (using `-d`) in the readme

**Comment by dionysius** [comment]
After that you will run into #12. Just tested the building locally

**Comment by Artim96** [comment]
> After that you will run into #12. Just tested the building locally

true

**Comment by dionysius** [comment]
You are right, it's currently in testing: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=rustup. So I will have options in the future to make this a bit less prone once it hits stable.

For now, this issue is solved and the package works as intended. The important bits have been documented in the readme. Lets head over to #12, I'll look into it.

**Comment by dionysius** [comment]
Thank you, will keep in mind. Will be fun when ubuntu and debian are out of sync again package wise. I can use the or operator `|` in build-depends which might suffice. For now i this source package must run for debian stable or ubuntu lts at least.

**Comment by dionysius** [comment]
Yep as hoped and expected `Build-Depends: rustup | cargo` works like a charm. Now you don't need `-d` anymore in buildpackage. Tested on trixie and booworm. See branch `main` or tag `debian/1.30.5-3`

**Comment by Artim96** [comment]
Yes, that does help.
