### ISSUE TITLE
What to do if a cargo dependency requires a newer rust-toolchain than rust-toolchain.toml is describing?

### ISSUE THREAD

**Issue by dionysius** [dionysius/vaultwarden-deb#12]
Currently vaultwarden v1.35.0 can't be built because it still has the toolchain listed for `1.76.0` in its [rust-toolchain.toml](https://github.com/dani-garcia/vaultwarden/blob/1.30.5/rust-toolchain.toml)

buildpackage will fail with an error similar:
>   package `migrations_internals v2.2.0` cannot be built because it requires rustc 1.78.0 or newer, while the currently active rustc version is 1.76.0

**Comment by dionysius** [comment]
Still digging through docs, but at a first glance `cargo install` seems not to use the package lock. Which explains the version inconsistencies for now. Still digging

**Comment by dionysius** [comment]
@Artim96 ^

**Comment by Artim96** [comment]
Package built without any further problems. Thanks!
