### ISSUE TITLE
process didn't exit successfully

### ISSUE THREAD

**Issue by Artim96** [dionysius/vaultwarden-deb#13]
I'm trying to compile the deb again in a Debian Stable VM, as I originally compiled it on Testing, but that won't be able to run on a Stable system. But the Stable systm doesn't have enough space for compiling. I've installed everything needed, including both the rust 1.78 toolchain via rustup and cargo (and with that the rust toolchain of Stable). For some reason toolchain 1.76 is being installed by the script (either by it or vaultwarden), but compilation fails with this message:
![Screenshot from 2024-06-06 11-16-49](https://github.com/dionysius/vaultwarden-deb/assets/16918678/73f797de-34b4-4728-a741-5f506b1d58e2)

**Comment by dionysius** [comment]
I see SIGKILL in your message. Something is killing the build process ftom outside. Is that a container or VM? Have a look into the /var/log/kern.log on your host system. Probably OOM (out-of-memory)

**Comment by dionysius** [comment]
Oh, and 1.76 is used because https://github.com/dani-garcia/vaultwarden/blob/1.30.5/rust-toolchain.toml describes it. But since the `--locked` fix from #12 this should not be an issue.

**Comment by dionysius** [comment]
Building this locally on my laptop (with other tools open and full desktop environment) the memory usage peaked at 19.2GB. There are several issues in cargo addressing memory issues, e.g.: https://github.com/rust-lang/cargo/issues/12912

**Comment by Artim96** [comment]
Right, compiling diesel_migrations and building the packages takes up loads of memory. In a VirtualBox VM on a very basic install from Debian Netinstall, it used 14.7 GB of memory (measured by GNU time). Was confused that compiling on an 8 GB machine on the other hand wasn't a problem. But loads of swap space does that for you.
