### ISSUE TITLE
Location configuration file

### ISSUE THREAD

**Issue by 0x233233** [dionysius/vaultwarden-deb#14]
Hi,

it's not a bug, i think it's only misleading.
In /etc/ exist an folder vaultwarden with no config file in it.
In /etc/default/ exist the vaultwarden config file.
So i think creating the vaultwarden directory is not necessary or change location of file from /etc/default/ to /etc/vaultwarden/.
And i think it is more clean to name it vaultwarden.env like it is writen in the file.

Thanks

**Comment by dionysius** [comment]
Yeah, /etc/vaultwarden was there when the package still generated the backend token automatically. Removed since it now makes more sense for the user to be aware how the token is configured.

I offer now a symlink there, was the easiest solution.
