### ISSUE TITLE
Permissions for /var/lib/vaultwarden/data missing

### ISSUE THREAD

**Issue by 0xErnie** [dionysius/vaultwarden-deb#3]
When starting vaultwarden the first time it throws an error, after trying to save the newly created key in /var/lib/vaultwarden/data.

It would help to change the owner of this folder to the vaultwarden user.

**Comment by dionysius** [comment]
Hmmm, technically its set to readwrite by systemd: https://github.com/dionysius/vaultwarden-deb/blob/main/debian/vaultwarden.service#L43

Let me check the systemd documentation

**Comment by dionysius** [comment]
And technically this should be the home folder of the vaultwarden user through https://github.com/dionysius/vaultwarden-deb/blob/main/debian/vaultwarden.postinst#L5
