### ISSUE TITLE
No version information

### ISSUE THREAD

**Issue by Peronia** [dionysius/vaultwarden-deb#7]
Hi,

I don't know if this issue is linked to your repo or the original vaultwarden.
But neither at the cmd or the admin page I can see the version I installed.

cmd:
```
root@host:~# vaultwarden -v
vaultwarden (Version info from Git not present)
```

web:
![grafik](https://github.com/dionysius/vaultwarden-deb/assets/25049991/12db4aa3-c7dd-438e-8151-31c1b578a4e0)

What is going wrong?

**Comment by dionysius** [comment]
Hi, I see the same, didn't notice.

As far as I'm aware debian packaging (or git-buildpackage) strips off all .git data when unpacking the source before compiling. I'll have a look into this.

**Comment by dionysius** [comment]
Seems like I need to set `VW_VERSION` at compile time:

- https://github.com/dani-garcia/vaultwarden/blob/main/src/main.rs#L139
- https://doc.rust-lang.org/std/macro.option_env.html

**Comment by dionysius** [comment]
Yes, this did the trick. https://github.com/dionysius/vaultwarden-deb/tree/debian/1.28.1-5 is the next release with the fix. Once github actions is finished, the release and its items should appear automatically
